name: Publish

on:
  push:
    branches:
      - 'master'

env:
  CACHE_VERSION: v1

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: publish to npmjs
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@api-types'
      - name: publish to GPR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
